/**
 * Canonical legacy-`defaults.json` migration for a project clone
 * (warren-5840, shared into `src/projects/` by warren-166d).
 *
 * One implementation of "convert `.warren/defaults.json` into the
 * warren-5840 YAML layout in place", shared by the
 * `POST /projects/:id/config-migrate` handler (server-side host clone,
 * so a remote CLI can migrate a project it cannot see on disk) and
 * `warren config migrate --cwd` (the operator's local checkout).
 * Before warren-166d this logic lived in
 * `src/cli/commands/config-migrate.ts`, which made the server-side
 * route impossible without a second copy.
 *
 * Mechanics:
 *   1. Read and schema-validate the legacy `defaults.json`.
 *   2. Pull any `preview` block out into a top-level `.warren/preview.yaml`.
 *   3. Write the remaining fields to `.warren/config.yaml`.
 *   4. Delete `.warren/defaults.json` (the deprecation source) so doctor /
 *      readyz / load no longer emit the deprecation warning on the next
 *      refresh.
 *
 * Refuses to clobber an existing `config.yaml` or `preview.yaml` — the
 * operator either already migrated (in which case `defaults.json` is stale
 * and should be deleted by hand) or has uncommitted edits we'd silently
 * lose. Schema failures in the source file abort the migrate with the
 * underlying error: a malformed `defaults.json` is fixed by editing, not
 * by converting.
 */

import { existsSync } from "node:fs";
import { readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { dump } from "js-yaml";
import { ValidationError } from "../core/errors.ts";
import {
	WARREN_CONFIG_DIR,
	WARREN_CONFIG_FILES,
	warrenConfigRelativePath,
} from "../warren-config/config.ts";
import {
	type DefaultsConfig,
	type PreviewConfig,
	parseDefaultsConfig,
} from "../warren-config/schema.ts";

const CONFIG_HEADER = `# .warren/config.yaml — per-project warren defaults (warren-5840 layout).
#
# Generated by 'warren config migrate' from .warren/defaults.json.
# See docs/design/warren-config.md for the schema.
`;

const PREVIEW_HEADER = `# .warren/preview.yaml — per-run preview environment (warren-5840, docs/design/preview-environments.md).
#
# Hoisted out of .warren/defaults.json by 'warren config migrate'. The
# top-level document is the preview block itself, not nested under a
# 'preview:' key.
`;

export interface MigrateWarrenDefaultsInput {
	/** Directory holding the `.warren/` dir to migrate (a project clone root). */
	readonly targetDir: string;
}

export interface MigrateWarrenDefaultsResult {
	/** Project-relative paths of the files written, in write order. */
	readonly written: string[];
	/** Whether a `preview` block was hoisted into `.warren/preview.yaml`. */
	readonly previewHoisted: boolean;
}

/**
 * Convert a clone's legacy `.warren/defaults.json` into
 * `.warren/config.yaml` (+ `.warren/preview.yaml` when a preview block
 * exists) and delete the source. Throws `ValidationError` when there is
 * nothing to migrate, when a target file already exists, or when the
 * source fails JSON parsing or schema validation.
 */
export async function migrateWarrenDefaults(
	input: MigrateWarrenDefaultsInput,
): Promise<MigrateWarrenDefaultsResult> {
	const warrenDir = join(input.targetDir, WARREN_CONFIG_DIR);
	const legacyAbs = join(warrenDir, WARREN_CONFIG_FILES.defaults);
	const configAbs = join(warrenDir, WARREN_CONFIG_FILES.config);
	const previewAbs = join(warrenDir, WARREN_CONFIG_FILES.preview);

	if (!existsSync(legacyAbs)) {
		throw new ValidationError(
			`nothing to migrate: ${warrenConfigRelativePath("defaults")} does not exist in ${warrenDir}`,
			{
				recoveryHint: "if you already migrated by hand, this is a no-op and you can ignore it",
			},
		);
	}
	if (existsSync(configAbs)) {
		throw new ValidationError(
			`refusing to overwrite existing ${warrenConfigRelativePath("config")} at ${configAbs}`,
			{
				recoveryHint:
					"resolve the existing config.yaml first (e.g. delete it after merging by hand), then re-run",
			},
		);
	}
	if (existsSync(previewAbs)) {
		throw new ValidationError(
			`refusing to overwrite existing ${warrenConfigRelativePath("preview")} at ${previewAbs}`,
			{
				recoveryHint:
					"resolve the existing preview.yaml first (e.g. delete it after merging by hand), then re-run",
			},
		);
	}

	const raw = await readFile(legacyAbs, "utf8");
	const trimmed = raw.trim();
	let document: unknown;
	if (trimmed === "") {
		document = undefined;
	} else {
		try {
			document = JSON.parse(raw);
		} catch (err) {
			throw new ValidationError(
				`failed to parse ${warrenConfigRelativePath("defaults")}: ${
					err instanceof Error ? err.message : String(err)
				}`,
				{
					recoveryHint:
						"fix the JSON syntax in defaults.json by hand, then re-run `warren config migrate`",
				},
			);
		}
	}

	const parsed = parseDefaultsConfig(document);
	if (!parsed.ok) {
		throw new ValidationError(
			`schema validation failed for ${warrenConfigRelativePath("defaults")}: ${parsed.message}`,
			{
				recoveryHint:
					"fix the schema violation in defaults.json by hand, then re-run `warren config migrate`",
			},
		);
	}

	const { configBlock, previewBlock } = splitPreview(parsed.value);

	const writtenFiles: string[] = [];
	const configBody = renderConfig(configBlock);
	await writeFile(configAbs, configBody, "utf8");
	writtenFiles.push(warrenConfigRelativePath("config"));

	if (previewBlock !== null) {
		const previewBody = renderPreview(previewBlock);
		await writeFile(previewAbs, previewBody, "utf8");
		writtenFiles.push(warrenConfigRelativePath("preview"));
	}

	await rm(legacyAbs, { force: true });

	return { written: writtenFiles, previewHoisted: previewBlock !== null };
}

function splitPreview(defaults: DefaultsConfig): {
	configBlock: DefaultsConfig;
	previewBlock: PreviewConfig | null;
} {
	const { preview, ...rest } = defaults;
	return {
		configBlock: rest,
		previewBlock: preview ?? null,
	};
}

function renderConfig(config: DefaultsConfig): string {
	if (Object.keys(config).length === 0) {
		return `${CONFIG_HEADER}{}\n`;
	}
	return `${CONFIG_HEADER}${dump(config, { lineWidth: 100, noRefs: true })}`;
}

function renderPreview(preview: PreviewConfig): string {
	return `${PREVIEW_HEADER}${dump(preview, { lineWidth: 100, noRefs: true })}`;
}
